name: "Multi Event Pipeline"
on:
    push:
        branches:
            - master
            - test
    pull_request:
        branches:
            - master
        types:
            - closed

    workflow_dispatch:

jobs:
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master/test push"
              run: echo "Running on master/test push"
    
    on-pull-request:
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request"
              run: echo "Running on pull request"
    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps:
            - name: "Running on pull request closed"
              run: echo "Running on pull request closed"

    on-workflow-dispatch:
        if: github.event_name == 'workflow dispatch'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on dispatch"
              run: echo "running on workflow dispatch"


